---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=999
      - PGID=999
      - TZ=Etc/UTC
    volumes:
      - /home/jellyfin/media:/data
      - /home/ubuntu/downloader/radarr/config:/config
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=999
      - PGID=999
      - TZ=Etc/UTC
    volumes:
      - /home/ubuntu/downloader/sonarr/config:/config
      #- /opt/data:/data
      - /home/jellyfin/media:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=999
      - PGID=999
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /home/ubuntu/downloader/jackett/config:/config
      - /home/jellyfin/media:/data
    ports:
      - 9117:9117
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=999
      - PGID=999
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /home/jellyfin/config:/config      #- /path/to/config:/config      - /path/to/library:/config
      - /home/jellyfin/media:/data
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=999
      - PGID=999
      - TZ=Etc/UTC
    volumes:
      - /home/ubuntu/downloader/transmission/config:/config
      - /home/jellyfin/media:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped